import StyleDictionary from 'style-dictionary';

StyleDictionary.registerFormat({
  name: 'twitch/css',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens;

    const isPrimitive = (t) =>
      !(t.path[0] === 'color' && t.path[1] === 'semantic') &&
      !(t.path[0] === 'typography' && t.path[1] === 'roles') &&
      t.value !== undefined;

    const primitives = tokens.filter(isPrimitive);

    const darkSemantic = tokens.filter(
      (t) =>
        t.path[0] === 'color' &&
        t.path[1] === 'semantic' &&
        t.path[2] === 'dark',
    );

    const lightSemantic = tokens.filter(
      (t) =>
        t.path[0] === 'color' &&
        t.path[1] === 'semantic' &&
        t.path[2] === 'light',
    );

    const v = (name, value) => `  --ds-${name}: ${value};`;

    return [
      '/* Auto-generated by Style Dictionary — do not edit manually */',
      '',
      ':root {',
      ...primitives.map((t) => v(t.name, t.value)),
      '',
      '  /* ── Semantic: dark theme (default) ── */',
      ...darkSemantic.map((t) => v(`color-${t.path[3]}`, t.value)),
      '}',
      '',
      '.light {',
      '  /* ── Semantic: light theme ── */',
      ...lightSemantic.map((t) => v(`color-${t.path[3]}`, t.value)),
      '}',
      '',
    ].join('\n');
  },
});

export default {
  source: ['tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/styles/',
      files: [
        {
          destination: 'tokens.css',
          format: 'twitch/css',
        },
      ],
    },
  },
};
